### ISSUE TITLE
help

### ISSUE THREAD

**Issue by m0iises19** [Selene-Desna/PACK_DrinkingFountain_CoffeeMachine_VendingMaching#1]
how to modify "esx_status"?

@poiivre

**Comment by poiivre** [comment]
well you get the esx_status script and modify the config file

**Comment by m0iises19** [comment]
How would you modify the file "config.cfg", could you give me some examples of how to do it please?

**Comment by m0iises19** [comment]
@poiivre 

![aaa](https://user-images.githubusercontent.com/10025085/124175040-5da19500-daad-11eb-9751-82deb4a8790e.png)
